### PR TITLE
add support path

### PR DESCRIPTION
**Pull request by dushaobindoudou**
add support path

### CODE REVIEW

**Comment by markwylde** [comment]
Looks good. So this fixes a bug that allows specifying a specific file path.

Happy to merge if you're finished?

**Review by markwylde — APPROVED** [review]

**Comment by dushaobindoudou** [comment]
I think I've finished and tested it。😊

**Comment by markwylde** [comment]
Awesome, thanks for your work @dushaobindoudou 

I'll merge it now, and make some minor linting changes, then release a new version.

**Comment by markwylde** [comment]
Released:
https://github.com/markwylde/esbuild-plugin-resolve/releases/tag/v1.0.3

**Pull request merged**
